# Generated by Django 4.2.10 on 2026-04-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_login_facebook_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_login_github_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_login_google_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserSocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("facebook", "Facebook"),
                            ("github", "GitHub"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User social account",
                "verbose_name_plural": "User social accounts",
                "db_table": "user_social_accounts",
                "ordering": ["provider", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_social_user_id_719c00_idx",
                    ),
                    models.Index(fields=["email"], name="user_social_email_66e8fe_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usersocialaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="accounts_social_provider_user_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersocialaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"), name="accounts_social_user_provider_uniq"
            ),
        ),
    ]
