# Generated by Django 4.2.10 on 2026-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sitesettings_social_login_facebook_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="signup_captcha_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="signup_disposable_email_blocking_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
