# Generated by Django 4.2.10 on 2026-05-02 15:05

from django.db import migrations, models


def disable_email_verification(apps, schema_editor):
    SiteSettings = apps.get_model("accounts", "SiteSettings")
    SiteSettings.objects.update(require_email_verification=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sitesettings_signup_captcha_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="require_email_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="signup_burst_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="signup_short_window_limit",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="signup_sustained_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.RunPython(
            disable_email_verification,
            migrations.RunPython.noop,
        ),
    ]
