#!/usr/bin/env python3
"""
Build ClauseChain_Technical_Memo.docx for the UN Global Hackathon submission.

- Generates 8 placeholder PNGs (light-gray panels with figure label + caption).
- Writes a .docx where each figure appears with the same filename + caption
  so the user can replace the image in Word (right-click -> Change Picture)
  without losing the figure numbering or caption.
"""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).parent
FIG_DIR = ROOT / "technical_memo_figures"
FIG_DIR.mkdir(exist_ok=True)
OUT_DOCX = ROOT / "ClauseChain_Technical_Memo.docx"

# ---------------------------------------------------------------------------
# Figures (filename, caption shown in docx, caption-overlay text inside PNG)
# ---------------------------------------------------------------------------
# Screenshot placeholders the user will replace in Word.
FIGURES = [
    ("fig01_dashboard.png",
     "Figure 1 — ClauseChain workspace dashboard.",
     "Workspace dashboard\n/dashboard"),
    ("fig02_pipeline_stepper.png",
     "Figure 2 — Nine-stage pipeline stepper (discover -> export) shown across all pipeline pages.",
     "Pipeline stepper\ndiscover -> export"),
    ("fig03_crawl_console.png",
     "Figure 3 — Crawl Console: politely-crawled candidate documents with type tags (HTML statute, native PDF, scanned PDF, regulator guideline, blocked).",
     "Crawl Console\n/pipeline/crawl"),
    ("fig04_harvest_review.png",
     "Figure 4 — Harvest Review: human keep/discard before expensive extraction begins.",
     "Harvest Review\n/pipeline/harvest"),
    ("fig05_extraction_ocr_diff.png",
     "Figure 5 — Extraction Workspace OCR diff: PaddleOCR-VL vs. Tesseract disagreement on a scanned Bengali page, with edit distance and confidence.",
     "Extraction Workspace\n/pipeline/extract  -  OCR diff"),
    ("fig06_mapping_run.png",
     "Figure 6 — Mapping Run: L0-L3 autonomy selector and the CVR (Cite / Verify / Reject) loop streaming clauses in real time.",
     "Mapping Run\n/pipeline/map  -  CVR loop"),
    ("fig07_source_trace.png",
     "Figure 7 — Source Trace: dual-panel synchronized scroll between extracted clauses and the original source, with per-gate dots, confidence, and match type.",
     "Source Trace\n/pipeline/trace  -  dual-panel sync"),
    ("fig08_export_output.png",
     "Figure 8 — Export Output: machine-readable records (JSON / CSV / JSONL) with discovery tags, CVR gate results, and verbatim citations.",
     "Export Output\n/pipeline/export"),
]

# Diagrams generated by build_diagrams.py — do NOT overwrite as placeholders.
DIAGRAM_ARCH = ("fig00_architecture.png",
                "Figure 0 — ClauseChain system architecture: ten-stage typed "
                "pipeline (left), eight verification gates G1-G8 mapped to "
                "the stage that produces the evidence each gate checks "
                "(right), and the local/cloud routing legend.")
DIAGRAM_CVR  = ("fig09_cvr_loop.png",
                "Figure 9 — CVR loop. A mapped clause flows left-to-right "
                "through the eight gates on the PASS lane; any uncertain "
                "outcome routes up to the REVIEW lane, any disqualifying "
                "result drops to the REJECT lane. Only PASS through all "
                "eight gates produces a VERIFIED exportable record.")

# ---------------------------------------------------------------------------
# 1. Create placeholder PNGs (16:9, 1600x900) the user will overwrite
# ---------------------------------------------------------------------------
def make_placeholder(path: Path, overlay_text: str) -> None:
    W, H = 1600, 900
    img = Image.new("RGB", (W, H), color=(240, 242, 247))      # cc-ink-50-ish
    draw = ImageDraw.Draw(img)

    # outer dashed-look border (two solid rectangles, inner offset)
    draw.rectangle([0, 0, W - 1, H - 1], outline=(180, 186, 196), width=4)
    draw.rectangle([24, 24, W - 25, H - 25], outline=(210, 215, 222), width=2)

    # corner brand chip
    chip_w, chip_h = 220, 56
    draw.rectangle([40, 40, 40 + chip_w, 40 + chip_h],
                   fill=(37, 99, 235))                          # cc-blue
    try:
        chip_font = ImageFont.truetype(
            "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 22)
    except OSError:
        chip_font = ImageFont.load_default()
    draw.text((58, 54), "ClauseChain", fill=(255, 255, 255), font=chip_font)

    # main label
    try:
        title_font = ImageFont.truetype(
            "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 64)
        sub_font = ImageFont.truetype(
            "/System/Library/Fonts/Supplemental/Arial.ttf", 32)
    except OSError:
        title_font = ImageFont.load_default()
        sub_font = ImageFont.load_default()

    lines = overlay_text.split("\n")
    title_line = lines[0]
    sub_line = lines[1] if len(lines) > 1 else ""

    # measure + center
    bbox_t = draw.textbbox((0, 0), title_line, font=title_font)
    tw, th = bbox_t[2] - bbox_t[0], bbox_t[3] - bbox_t[1]
    bbox_s = draw.textbbox((0, 0), sub_line, font=sub_font)
    sw, sh = bbox_s[2] - bbox_s[0], bbox_s[3] - bbox_s[1]

    total_h = th + 20 + sh
    cx = W // 2
    cy = H // 2

    draw.text((cx - tw // 2, cy - total_h // 2),
              title_line, fill=(31, 41, 55), font=title_font)
    draw.text((cx - sw // 2, cy - total_h // 2 + th + 20),
              sub_line, fill=(107, 114, 128), font=sub_font)

    # footer hint
    try:
        hint_font = ImageFont.truetype(
            "/System/Library/Fonts/Supplemental/Arial.ttf", 22)
    except OSError:
        hint_font = ImageFont.load_default()
    hint = "Placeholder - replace with screenshot (right-click -> Change Picture in Word)"
    bbox_h = draw.textbbox((0, 0), hint, font=hint_font)
    hw = bbox_h[2] - bbox_h[0]
    draw.text((cx - hw // 2, H - 70), hint, fill=(140, 146, 156), font=hint_font)

    img.save(path, "PNG", optimize=True)


print("Generating placeholder figures...")
for filename, _caption, overlay in FIGURES:
    make_placeholder(FIG_DIR / filename, overlay)
    print(f"  {filename}")

# ---------------------------------------------------------------------------
# 2. Build the .docx
# ---------------------------------------------------------------------------
doc = Document()

# Page margins: 0.8 inch all round (tighter to leave more room)
for section in doc.sections:
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)

# Normal style: Calibri 11
normal = doc.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(11)

# Heading styles
for level, size in [(1, 16), (2, 12)]:
    s = doc.styles[f"Heading {level}"]
    s.font.name = "Calibri"
    s.font.size = Pt(size)
    s.font.bold = True
    s.font.color.rgb = RGBColor(0x1F, 0x29, 0x37)


def add_caption(text: str) -> None:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x55, 0x5B, 0x66)
    p.paragraph_format.space_after = Pt(10)


def add_figure(filename: str, caption: str, width_in: float = 6.2) -> None:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(str(FIG_DIR / filename), width=Inches(width_in))
    p.paragraph_format.space_after = Pt(2)
    add_caption(caption)


def add_table(headers, rows):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = "Light Grid Accent 1"
    table.alignment = WD_ALIGN_PARAGRAPH.CENTER
    hdr_cells = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr_cells[i].text = ""
        run = hdr_cells[i].paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(10)
    for r_idx, row in enumerate(rows, start=1):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx].cells[c_idx]
            cell.text = ""
            run = cell.paragraphs[0].add_run(val)
            run.font.size = Pt(9)
    doc.add_paragraph()  # spacer


# ---- TITLE BLOCK ---------------------------------------------------------
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
title_run = title.add_run("ClauseChain — Technical Memo")
title_run.bold = True
title_run.font.size = Pt(20)
title_run.font.color.rgb = RGBColor(0x1F, 0x29, 0x37)

sub = doc.add_paragraph()
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
sub_run = sub.add_run(
    "Measured Legal Evidence for Digital Trade  |  UN Global Hackathon: "
    "AI for Digital Trade Regulatory Analysis  |  RDTII Pillars 6, 7, 8, 9"
)
sub_run.italic = True
sub_run.font.size = Pt(10)
sub_run.font.color.rgb = RGBColor(0x55, 0x5B, 0x66)

# ---- LEAD PARAGRAPH ------------------------------------------------------
lead = doc.add_paragraph()
lead.add_run(
    "ClauseChain is an open-source AI pipeline that maps digital trade "
    "regulation to the UN RDTII framework. Its thesis is that citation "
    "alone is not enough: a real quote can come from a repealed act, a "
    "non-binding guideline, an unofficial translation, or a clause whose "
    "exception changes the rule. ClauseChain verifies the whole evidence "
    "chain — span, source authority, current-law status, legal structure, "
    "predicate meaning, and counter-evidence — before any output ships."
)

add_figure("fig01_dashboard.png", FIGURES[0][1])

# ---- §1 ARCHITECTURE -----------------------------------------------------
doc.add_heading("1. Proposed System Architecture", level=1)

add_figure(DIAGRAM_ARCH[0], DIAGRAM_ARCH[1], width_in=6.4)

doc.add_paragraph(
    "ClauseChain is a ten-stage typed pipeline (Figure 0). Each stage "
    "emits a structured artifact and a measurable quality signal:"
)

stages = [
    ("0 Jurisdiction Pack",  "authority hierarchy, seed sources, citation patterns, language config, RDTII rubric"),
    ("1 Discovery",          "polite crawl of official statute databases, gazettes, regulator portals"),
    ("2 Acquisition",        "raw bytes, SHA-256, HTTP headers, rendered page images"),
    ("3 Authority Resolver", "binding / draft / repealed / consolidated / amendment / translation classification"),
    ("4 Extraction + OCR",   "HTML / native PDF / scanned PDF with text, bbox, per-token confidence"),
    ("5 Structure + Rule Units", "section tree plus principal-rule + exception + condition binding"),
    ("6 Retrieval",          "hybrid BM25 + multilingual dense + cross-encoder rerank"),
    ("7 Predicate Extraction", "actor / action / object / modality / condition / exception tuple"),
    ("8 RDTII Mapping",      "rubric-as-code deterministic checks + constrained classifier"),
    ("9 Verification Gates", "eight gates G1-G8 (span, location, authority, currentness, structure, tuple, RDTII, counter-evidence)"),
    ("10 Audit + Export",    "review UI, JSONL / CSV / Markdown / provenance bundle"),
]
add_table(["Stage", "Responsibility"], stages)

doc.add_paragraph(
    "The application surface lives at /dashboard plus six pipeline routes: "
    "/pipeline/{crawl, harvest, extract, map, trace, export}. A working "
    "Next.js 16 / React 19 / TypeScript prototype is in-repo and is what "
    "every figure in this memo screenshots."
)

add_figure("fig02_pipeline_stepper.png", FIGURES[1][1])

# ---- §2 TOOLS, MODELS, METHODS ------------------------------------------
doc.add_heading("2. Tools, Models, and Methods", level=1)

doc.add_paragraph(
    "ClauseChain is local-first on a single L40S-class GPU, with per-task "
    "optional cloud routing to OpenAI or Anthropic. All demo documents are "
    "public legal text from official portals, so operators may safely mix "
    "local and cloud per pipeline step."
)

model_rows = [
    ("Crawling",             "Scrapy + Playwright + Crawl4AI",     "n/a (deterministic)"),
    ("HTML extraction",      "Trafilatura + legal DOM parser",     "n/a"),
    ("PDF extraction",       "Docling + PyMuPDF",                  "n/a"),
    ("OCR + bbox",           "PaddleOCR-VL / PaddleOCR",           "n/a (coordinate-native)"),
    ("OCR repair (VLM)",     "Qwen2-VL-7B",                        "gpt-4o or claude-sonnet-4-6"),
    ("Embeddings",           "BGE-M3 / Qwen3-Embedding",           "text-embedding-3-large"),
    ("Reranking",            "BGE-reranker-v2-m3",                 "LLM-as-judge"),
    ("Predicate extraction", "Qwen2.5-7B / Llama-3.1-8B-Instruct", "gpt-4.1 or claude-sonnet-4-6"),
    ("RDTII mapping",        "Qwen2.5-7B",                         "gpt-4.1 or claude-sonnet-4-6"),
    ("NLI verifier (G6/G7)", "DeBERTa-v3 multilingual NLI",        "gpt-4o or claude-sonnet-4-6"),
]
add_table(["Task", "Local default", "Cloud option"], model_rows)

doc.add_paragraph(
    "Serving stack: vLLM for local LLMs; FastAPI services; Celery / RQ "
    "workers; Postgres + pgvector; OpenSearch (BM25) + Qdrant (dense); "
    "MinIO object storage; Next.js audit UI; Docker Compose for the "
    "prototype. Routing modes per task: always_local, always_cloud, "
    "confidence_threshold, confidence_margin."
)

add_figure("fig03_crawl_console.png",   FIGURES[2][1])
add_figure("fig04_harvest_review.png",  FIGURES[3][1])
add_figure("fig05_extraction_ocr_diff.png", FIGURES[4][1])
add_figure("fig06_mapping_run.png",     FIGURES[5][1])

# ---- §3 ACCURACY / TRANSPARENCY / COST ----------------------------------
doc.add_heading("3. Accuracy, Transparency, and Cost-Efficiency", level=1)

doc.add_heading("Accuracy — eight verification gates", level=2)

add_figure(DIAGRAM_CVR[0], DIAGRAM_CVR[1], width_in=6.4)

doc.add_paragraph(
    "Figure 9 shows the CVR loop. Every claim runs G1 Span (exact byte "
    "match, or OCR-fuzzy edit distance <= 3 in OCR regions only), G2 "
    "Location (bbox IoU >= 0.85 or section-path match), G3 Authority "
    "(binding tier rank <= 5; guidelines never support binding claims), "
    "G4 Currentness (not repealed, draft, or superseded), G5 Structure "
    "(correct legal unit with exception present), G6 Tuple (multilingual "
    "NLI >= 0.70 across populated predicate fields), G7 RDTII (required "
    "rubric predicates present, no exclusion triggered), G8 "
    "Counter-evidence (corpus search for repeal, amendment, conflict, "
    "definition shift). Any failure rejects or routes to human review. "
    "Per-stage metrics — discovery recall@20, OCR CER, section-boundary "
    "F1, retrieval recall@20, tuple field accuracy, pillar macro-F1, "
    "citation exact-match, abstention calibration — are reported with "
    "bootstrap confidence intervals against five baselines."
)

add_figure("fig07_source_trace.png", FIGURES[6][1])

doc.add_heading("Transparency — provenance bundle", level=2)
doc.add_paragraph(
    "Every exported record carries: source URL, raw-source SHA-256, "
    "retrieval timestamp, section, page, char offsets, bbox where "
    "available, verbatim quote, span SHA-256, OCR confidence, the eight "
    "gate results, and model identity (e.g. local:Qwen2.5-7B or "
    "cloud:anthropic:claude-sonnet-4-6). A second analyst on a different "
    "machine can re-verify every claim from the provenance bundle alone."
)

add_figure("fig08_export_output.png", FIGURES[7][1])

doc.add_heading("Cost-efficiency", level=2)
doc.add_paragraph(
    "Local-first default avoids per-token cost entirely. Expensive VLM "
    "repair runs only on low-confidence OCR regions; cross-encoder "
    "reranking and NLI verification run on small candidate sets, not the "
    "full corpus. Cloud escalation is opt-in, per-task, and capped by a "
    "per-run USD budget; when the cap hits, the pipeline falls back to "
    "local automatically and logs the cap event. Documents tagged "
    "'restricted' in the jurisdiction pack refuse cloud routing entirely. "
    "Per-run cost is reported by task and provider so operators can tune "
    "the local-vs-cloud split per pipeline."
)

# ---- SAVE ----------------------------------------------------------------
doc.save(OUT_DOCX)
print(f"\nWrote {OUT_DOCX}")
print(f"Placeholders in {FIG_DIR}/ (8 files, 16:9, 1600x900)")
