# Generated by Django 4.2.10 on 2026-03-16 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_default_plans(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")

    default_plans = [
        {
            "slug": "free",
            "defaults": {
                "name": "Free",
                "tier": 0,
                "max_items": 3,
                "price_monthly": 0,
                "price_yearly": 0,
                "bkash_price_monthly": 0,
                "bkash_price_yearly": 0,
                "currency": "USD",
                "is_active": True,
                "features": [
                    "Up to 3 items",
                    "Basic features",
                    "Community support",
                ],
            },
        },
        {
            "slug": "pro",
            "defaults": {
                "name": "Pro",
                "tier": 1,
                "max_items": 25,
                "price_monthly": 29,
                "price_yearly": 290,
                "bkash_price_monthly": 2900,
                "bkash_price_yearly": 29000,
                "currency": "USD",
                "is_active": True,
                "features": [
                    "Up to 25 items",
                    "All Pro features",
                    "Priority support",
                ],
            },
        },
        {
            "slug": "enterprise",
            "defaults": {
                "name": "Enterprise",
                "tier": 2,
                "max_items": 0,
                "price_monthly": 99,
                "price_yearly": 990,
                "bkash_price_monthly": 9900,
                "bkash_price_yearly": 99000,
                "currency": "USD",
                "is_active": True,
                "features": [
                    "Unlimited items",
                    "All Enterprise features",
                    "Dedicated support",
                ],
            },
        },
    ]

    for plan in default_plans:
        Plan.objects.update_or_create(slug=plan["slug"], defaults=plan["defaults"])


def backfill_user_subscriptions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Plan = apps.get_model("subscriptions", "Plan")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")

    free_plan = Plan.objects.filter(slug="free").first()
    if free_plan is None:
        return

    subscribed_user_ids = set(UserSubscription.objects.values_list("user_id", flat=True))
    missing_user_ids = [
        user_id
        for user_id in User.objects.values_list("id", flat=True)
        if user_id not in subscribed_user_ids
    ]

    UserSubscription.objects.bulk_create(
        [
            UserSubscription(
                user_id=user_id,
                plan_id=free_plan.id,
                status="active",
                billing_cycle="monthly",
                payment_provider="none",
            )
            for user_id in missing_user_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("tier", models.PositiveIntegerField(unique=True)),
                ("max_items", models.PositiveIntegerField(default=0, help_text="Max main-entity items. 0 = unlimited.")),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_yearly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bkash_price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bkash_price_yearly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tier"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past due"),
                            ("trialing", "Trialing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("stripe", "Stripe"),
                            ("bkash", "Bkash"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bkash_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RunPython(seed_default_plans, migrations.RunPython.noop),
        migrations.RunPython(backfill_user_subscriptions, migrations.RunPython.noop),
    ]
