# Generated by Django 4.2.10 on 2026-03-17 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_subscription_events(apps, schema_editor):
    SubscriptionEvent = apps.get_model("subscriptions", "SubscriptionEvent")
    UserSubscription = apps.get_model("subscriptions", "UserSubscription")

    events = []
    for subscription in UserSubscription.objects.select_related("plan", "user"):
        events.append(
            SubscriptionEvent(
                subscription_id=subscription.pk,
                user_id=subscription.user_id,
                event_type="baseline",
                plan_id=subscription.plan_id,
                status=subscription.status,
                payment_provider=subscription.payment_provider,
                billing_cycle=subscription.billing_cycle,
                metadata={
                    "current_period_start": (
                        subscription.current_period_start.isoformat()
                        if subscription.current_period_start
                        else None
                    ),
                    "current_period_end": (
                        subscription.current_period_end.isoformat()
                        if subscription.current_period_end
                        else None
                    ),
                    "cancel_at_period_end": subscription.cancel_at_period_end,
                },
            )
        )

    if events:
        SubscriptionEvent.objects.bulk_create(events, batch_size=500)


def reverse_backfill_subscription_events(apps, schema_editor):
    SubscriptionEvent = apps.get_model("subscriptions", "SubscriptionEvent")
    SubscriptionEvent.objects.filter(event_type="baseline").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0002_usersubscription_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline"),
                            ("admin_override", "Admin override"),
                            ("stripe_sync", "Stripe sync"),
                            ("stripe_past_due", "Stripe past due"),
                            ("stripe_cancelled", "Stripe cancelled"),
                            ("bkash_activated", "bKash activated"),
                            ("bkash_cancel_requested", "bKash cancel requested"),
                            ("bkash_downgraded", "bKash downgraded"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past due"),
                            ("trialing", "Trialing"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("stripe", "Stripe"),
                            ("bkash", "Bkash"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_events",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="subscriptio_user_id_317692_idx",
                    ),
                    models.Index(
                        fields=["subscription", "created_at"],
                        name="subscriptio_subscri_3f832a_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="subscriptio_event_t_7298b9_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_subscription_events,
            reverse_backfill_subscription_events,
        ),
    ]
