# Generated by Django 4.2.10 on 2026-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscriptionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_sku",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("none", "Not refunded"),
                    ("pending", "Refund pending"),
                    ("completed", "Refunded"),
                    ("failed", "Refund failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refund_trx_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="bkashtransaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline"),
                    ("admin_override", "Admin override"),
                    ("stripe_sync", "Stripe sync"),
                    ("stripe_past_due", "Stripe past due"),
                    ("stripe_cancelled", "Stripe cancelled"),
                    ("bkash_activated", "bKash activated"),
                    ("bkash_cancel_requested", "bKash cancel requested"),
                    ("bkash_downgraded", "bKash downgraded"),
                    ("bkash_refunded", "bKash refunded"),
                ],
                max_length=40,
            ),
        ),
    ]
